spring.application.name=EmployeeManagementSystem

server.port=${PORT:8082}

spring.datasource.url=jdbc:postgresql://ep-jolly-brook-b3robvsb-pooler.c-4.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Y2UCsZj7VfvD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true